### PR TITLE
Feat/widgets onboarding

### PR DESCRIPTION
**Pull request by Nuhvi**
Simulator Screen Shot - iPhone 13 - 2022-10-14 at 17 41 58

### CODE REVIEW

**Comment by pwltr** [comment]
- Nav actions not working
- Title "Profile" should be changed/removed
- check copy

Simulator Screen Shot - iPhone 13 - 2022-10-17 at 10 40 12

**Review by limpbrains — APPROVED** [review]

**Review by limpbrains — CHANGES_REQUESTED** [review]
Need to fix issues Philipp mentioned

**Comment by Nuhvi** [comment]
@pwltr not sure how to fix the back button on the first slide of onboarding!

**Comment by pwltr** [comment]
Fixed here https://github.com/synonymdev/bitkit/pull/515/commits/8795816dfda2e283679ad0919b4e276125ad0d1a

**Review by limpbrains — APPROVED** [review]

**Pull request merged**
