### PR TITLE
feat: replace buildcache with ccache

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

Please include a summary of changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Linked Issues/Tasks

Add any links to GitHub issues or Asana tasks that are relevant to this pull request.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [ ] No test

### Screenshot / Video

Insert relevant screenshot / recording

### QA Notes

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce during the Bitkit testing session. You can also leave a video of the PR in action.

### CODE REVIEW

**Comment by limpbrains** [comment]
image

image

**Comment by limpbrains** [comment]
First run after ccache:
Build time 5m
```
ccache stats
  /usr/local/bin/ccache -s
  Cacheable calls:   2170 / 2170 (100.0%)
    Hits:            2170 / 2170 (100.0%)
      Direct:        2170 / 2170 (100.0%)
      Preprocessed:     0 / 2170 ( 0.00%)
    Misses:             0 / 2170 ( 0.00%)
  Local storage:
    Cache size (GB):  0.5 /  0.5 (97.24%)
    Hits:            2170 / 2170 (100.0%)
    Misses:             0 / 2170 ( 0.00%)
```

**Comment by ovitrif** [comment]
@limpbrains Any reasons why we wouldn't merge this sooner rather than later?
I can help w/ reviewing, though IMHO it's more like if the CI works then things must work 🤷🏻

**Comment by limpbrains** [comment]
It did not provide any noticeable speed improvement that I was hoping for, only adding complexity. I will revisit after we get a new Mac for testing.

**Comment by ovitrif** [comment]
> It did not provide any noticeable speed improvement that I was hoping for, only adding complexity. I will revisit after we get a new Mac for testing.

Gotcha, I agree w/ your point though :)
Maybe worth revisiting if now that we're on new RN speed differences are more obvious 🤔

**Pull request closed without merging**
