### PR TITLE
fix: remove flipper during e2e tests

### PR DESCRIPTION
**Pull request by limpbrains**
# Description

remove Flipper during e2e tests 

---

## Type of change

Bug fix

## Tests

Detox test

## QA Notes

Nothing to QA here

### CODE REVIEW

**Comment by pwltr** [comment]
To fix the modal bug we need to revert [this commit](https://github.com/synonymdev/bitkit/pull/982/commits/250690c31bdce9277e4839a99c626e49b3671855). I thought it was fixed in the latest RN version but looks like it's still there 👀 

We can probably move to native Alert in the next step which should work.

**Comment by pwltr** [comment]
Have you seen this? Maybe a cleaner solution
https://dev.to/retyui/disable-flipper-on-ci-builds-for-react-native-complete-guide-bnd

**Comment by limpbrains** [comment]
> Have you seen this? Maybe a cleaner solution https://dev.to/retyui/disable-flipper-on-ci-builds-for-react-native-complete-guide-bnd

Thx, will try!

**Comment by limpbrains** [comment]
Indeed, NO_FLIPPER is much cleaner. I also removed unused cache config, now the job is 10 min faster.
I will try to add them back later, after benchmarking

**Review by pwltr — APPROVED** [review]

**Pull request merged**
