### PR TITLE
Decrease Address Generation Time

### PR DESCRIPTION
**Pull request by coreyphillips**
This PR:
- Implements `nodejs-mobile-react-native`.
- Wraps the following methods: `generateMnemonic`, `getPrivateKey`, `getScriptHash`, `getAddress`.
- The app will now generate 5 `addresses` and 5 `changeAddresses` on start.
    - Eventually we'll want to bump this to twenty to match the gap limit standard.
- Added logic to the `subscribeToAddresses` method to ensure we are watching behind and ahead of the current address index by the set gap limit or highest address count available if less than the current gap limit.

### CODE REVIEW

**Comment by limpbrains** [comment]
Can't build it for iOS on my machine. Did a fresh install. 

```
warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/jdenticon/package.json
warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/random-access-web-storage/package.json
warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/nano-staged/package.json
info Found Xcode workspace "bitkit.xcworkspace"
info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
2022-10-10 16:29:29.464 xcodebuild[58547:7895351] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-astoxmjzuookvedkozxfyiosokdh/Build/Products/Debug-iphonesimulator/bitkit.app"
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
Не удается установить «Bitkit»
Повторите попытку позже.
invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.U2nj7i/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
Underlying error (domain=MIInstallerErrorDomain, code=70):
	invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.U2nj7i/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
info Launching "to.synonym.bitkit.testnet"
success Successfully launched the app on the simulator
```

error in metro:
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 LOG  i18next: languageChanged ru-US
 LOG  i18next: initialized {"appendNamespaceToCIMode": false, "appendNamespaceToMissingKey": false, "cache": {"enabled": true}, "compatibilityJSON": "v3", "contextSeparator": "_", "debug": true, "defaultNS": "common", "fallbackLng": ["en"], "fallbackNS": false, "ignoreJSONStructure": true, "initImmediate": true, "interpolation": {"escapeValue": false, "format": [Function bound format], "formatSeparator": ",", "maxReplaces": 1000, "nestingOptionsSeparator": ",", "nestingPrefix": "$t(", "nestingSuffix": ")", "prefix": "{{", "skipOnVariables": true, "suffix": "}}", "unescapePrefix": "-"}, "joinArrays": false, "keySeparator": ".", "lng": "ru-US", "load": "all", "missingInterpolationHandler": false, "missingKeyHandler": false, "nonExplicitSupportedLngs": false, "ns": ["en"], "nsSeparator": ":", "overloadTranslationOptionHandler": [Function handle], "parseMissingKeyHandler": false, "partialBundledLanguages": false, "pluralSeparator": "_", "postProcess": false, "postProcessPassResolved": false, "preload": false, "resources": {"en": {"activity": [Object], "common": [Object], "menu": [Object], "profile": [Object], "wallets": [Object]}}, "returnEmptyString": true, "returnNull": true, "returnObjects": false, "returnedObjectHandler": false, "saveMissing": false, "saveMissingPlurals": true, "saveMissingTo": "fallback", "simplifyPluralSuffix": true, "supportedLngs": false, "updateMissing": false}
 ERROR  TypeError: Cannot read property 'startNodeProject' of null, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

```
/Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.U2nj7i/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
```
Doesn't exist

**Comment by pwltr** [comment]
I also get the symlink error when building for iOS, can't remember what fixed it last time. Android works now, tested on emulator and device.

**Comment by coreyphillips** [comment]
@pwltr @limpbrains, I think the previous `yarn.lock` merge might have been botched. They should be aligned as of [this](https://github.com/synonymdev/bitkit/pull/483/commits/1676203774cff791ec8be392cc07a33ade56d658) commit.

**Comment by limpbrains** [comment]
I've got the same error
```
warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/jdenticon/package.json
warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/random-access-web-storage/package.json
warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/nano-staged/package.json
info Found Xcode workspace "bitkit.xcworkspace"
info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
2022-10-10 18:13:15.711 xcodebuild[84181:8000481] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-astoxmjzuookvedkozxfyiosokdh/Build/Products/Debug-iphonesimulator/bitkit.app"
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
Не удается установить «Bitkit»
Повторите попытку позже.
invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.Ia6EBS/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
Underlying error (domain=MIInstallerErrorDomain, code=70):
	invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.Ia6EBS/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
info Launching "to.synonym.bitkit.testnet"
success Successfully launched the app on the simulator
```

**Comment by coreyphillips** [comment]
> I've got the same error
> 
> ```
> warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/jdenticon/package.json
> warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/random-access-web-storage/package.json
> warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/bitkit/node_modules/nano-staged/package.json
> info Found Xcode workspace "bitkit.xcworkspace"
> info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
> success Successfully built the app
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
> { platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
> { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
> 2022-10-10 18:13:15.711 xcodebuild[84181:8000481] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
> info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-astoxmjzuookvedkozxfyiosokdh/Build/Products/Debug-iphonesimulator/bitkit.app"
> An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
> Не удается установить «Bitkit»
> Повторите попытку позже.
> invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.Ia6EBS/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
> Underlying error (domain=MIInstallerErrorDomain, code=70):
> 	invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.Ia6EBS/extracted/Payload/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
> info Launching "to.synonym.bitkit.testnet"
> success Successfully launched the app on the simulator
> ```

Have you tried resetting your cache or spinning up a clean build? May need to "Device"->"Erase All Content and Settings" in the simulator as well.
```
mkdir nodejs-mobile-pr && cd nodejs-mobile-pr && git clone git@github.com:synonymdev/bitkit.git && cd bitkit && git checkout nodejs-mobile-update && yarn install && yarn ios
```

**Comment by limpbrains** [comment]
same error, I did reset the emulator and copy-pasted you command
```
~/s/nodejs-mobile-pr/bitkit  npx react-native run-ios --udid="F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA"       nodejs-mobile-update warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/nodejs-mobile-pr/bitkit/node_modules/jdenticon/package.json
warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/nodejs-mobile-pr/bitkit/node_modules/random-access-web-storage/package.json
warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/nodejs-mobile-pr/bitkit/node_modules/nano-staged/package.json
info Found Xcode workspace "bitkit.xcworkspace"
info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
2022-10-10 19:09:58.175 xcodebuild[15559:8118746] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-ctwvcgrypagfrshktzdvmlihouix/Build/Products/Debug-iphonesimulator/bitkit.app"
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
Unable To Install “Bitkit”
Please try again later.
invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.wcYzqW/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
Underlying error (domain=MIInstallerErrorDomain, code=70):
	invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.wcYzqW/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
info Launching "to.synonym.bitkit.testnet"
error Failed to launch the app on simulator, An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "to.synonym.bitkit.testnet" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "to.synonym.bitkit.testnet" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
	Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
```

**Comment by coreyphillips** [comment]
@limpbrains, I reverted the non-essential changes from yarn.lock that may be impacting the build. Does the following successfully get a fresh build working for you?

```
watchman watch-del-all && yarn cache clean && mkdir nodejs-mobile-update && cd nodejs-mobile-update && git clone git@github.com:synonymdev/bitkit.git && cd bitkit && git checkout nodejs-mobile-update && yarn install && yarn ios
```

**Comment by limpbrains** [comment]
same error

**Comment by coreyphillips** [comment]
Reinstalling/readding `nodejs-mobile-react-native` yielded the changes [here](https://github.com/synonymdev/bitkit/pull/483/commits/e8109962f15527657aeb0b1e09b3cbfd5f99fc90).

I've been able to successfully build the branch across multiple machines and have the sneaking suspicion there's a caching issue at play. As a final attempt, please remove/clear the `DerivedData` folder and let me know the results of the following:

```
rm -rf ${TMPDIR:-/tmp}/metro-* && watchman watch-del-all && yarn cache clean && pod cache clean --all && mkdir another-nodejs-mobile-attempt && cd another-nodejs-mobile-attempt && git clone git@github.com:synonymdev/bitkit.git && cd bitkit && git checkout nodejs-mobile-update && yarn install && yarn ios
```

If that fails please try the following:

```
cd ios && pod deintegrate && pod install && cd ../ && yarn ios
```

If that also fails, I believe I'm at a loss and may need to go back to the drawing board.

Thanks for your patience with me on this one guys.

**Comment by limpbrains** [comment]
- rebooted, just in case :)
- DerivedData removed
- all caches were cleaned
- same error :(

```
warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/jdenticon/package.json
warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/random-access-web-storage/package.json
warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/nano-staged/package.json
info Found Xcode workspace "bitkit.xcworkspace"
info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
2022-10-11 12:07:26.163 xcodebuild[16738:84151] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-bxlhbvpqcdssncbgkbkazwehhsth/Build/Products/Debug-iphonesimulator/bitkit.app"
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
Unable To Install “Bitkit”
Please try again later.
invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.37eiVT/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
Underlying error (domain=MIInstallerErrorDomain, code=70):
    invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.37eiVT/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
info Launching "to.synonym.bitkit.testnet"
error Failed to launch the app on simulator, An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "to.synonym.bitkit.testnet" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "to.synonym.bitkit.testnet" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
    The operation couldn’t be completed. Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
    Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
```

Could it be related to any other local package? python?

**Comment by coreyphillips** [comment]
> * rebooted, just in case :)
> * DerivedData removed
> * all caches were cleaned
> * same error :(
> 
> ```
> warn Package jdenticon has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/jdenticon/package.json
> warn Package random-access-web-storage has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/random-access-web-storage/package.json
> warn Package nano-staged has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/limpbrains/s/another-nodejs-mobile-attempt/bitkit/node_modules/nano-staged/package.json
> info Found Xcode workspace "bitkit.xcworkspace"
> info Building (using "xcodebuild -workspace bitkit.xcworkspace -configuration Debug -scheme bitkit -destination id=F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA")
> success Successfully built the app
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
> { platform:iOS Simulator, id:F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA, OS:16.0, name:iPhone 14 Pro }
> { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
> 2022-10-11 12:07:26.163 xcodebuild[16738:84151] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
> info Installing "/Users/limpbrains/Library/Developer/Xcode/DerivedData/bitkit-bxlhbvpqcdssncbgkbkazwehhsth/Build/Products/Debug-iphonesimulator/bitkit.app"
> An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
> Unable To Install “Bitkit”
> Please try again later.
> invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.37eiVT/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
> Underlying error (domain=MIInstallerErrorDomain, code=70):
>     invalid symlink at /Users/limpbrains/Library/Developer/CoreSimulator/Devices/F7AAC9DB-E768-4C62-8C02-495A1E4B9DFA/data/Library/Caches/com.apple.mobile.installd.staging/temp.37eiVT/extracted/bitkit.app/nodejs-project/node_modules/tiny-secp256k1/build/node_gyp_bins/python3
> info Launching "to.synonym.bitkit.testnet"
> error Failed to launch the app on simulator, An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> The request to open "to.synonym.bitkit.testnet" failed.
> The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "to.synonym.bitkit.testnet" is unknown to FrontBoard").
> Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
>     The operation couldn’t be completed. Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
>     Application "to.synonym.bitkit.testnet" is unknown to FrontBoard.
> ```
> 
> Could it be related to any other local package? python?

It's possible. A `brew upgrade` wouldn't hurt. Another quick search also suggested trying a new iOS simulator.

**Comment by pwltr** [comment]
Switched to `node@16` and now it runs!

**Review by pwltr — APPROVED** [review]

**Comment by limpbrains** [comment]
I can confirm. Node v16 works fine!

**Review by limpbrains — APPROVED** [review]

**Comment by pwltr** [comment]
FYI, the latest LTS `v16.18.0` also doesn't work. So maybe there is something in the changelog that let's us understand better: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#16.18.0

**Pull request merged**
