### PR TITLE
feat: upgrade Slashpay

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

Upgrade Slashpay to new Slashtags
Also use npm slashtags packages

### Linked Issues/Tasks

https://app.asana.com/0/1189635884316057/1205132559090587/f

### Type of change

Refactoring

### Tests

No test

### CODE REVIEW

**Comment by pwltr** [comment]
I missed this for the previous PR but when trying to edit a contact's name it is resetting the field.

https://github.com/synonymdev/bitkit/assets/8538369/adbce328-565a-4441-a8f1-946e5d72be89

**Comment by pwltr** [comment]
Also Slashpay still doesn't work reliably for me. I'm trying to pay from Wallet A to Wallet B and it works 50% of the time but Wallet B to A never works. Not sure if this is because maybe Slashpay config has not been updated or because of routing issue so would not block this PR because of that but something to look into.

https://github.com/synonymdev/bitkit/assets/8538369/acea4bfa-8d32-4d56-a005-d3e5a03a0351

Related: https://github.com/synonymdev/bitkit/issues/1129

**Comment by limpbrains** [comment]
- corrected contact name editing bug.
- resolved unreliability issues in Slashpay by adding ﻿{ skipCache: true } to the Slashtags client.

**Review by pwltr — APPROVED** [review]
Nice, working great now!

**Pull request merged**
