### PR TITLE
fix(ui): NumberPad + various fixes

### LINKED ISSUE #263: Send: NumberPad fiat amount issue
**Describe the bug**
Typing a dollar amount into the NumberPad with more than 5 digits resets the input

**To Reproduce**
1. Go to Send Flow
2. Click on the amount
4. Type in something like 1111111

**Expected behavior**
Amount shows as 11,111.11

**Screenshots**
https://user-images.githubusercontent.com/8538369/185458941-b5ec2cfc-5355-4883-83d0-18bd319d15c3.mp4

**Additional context**
Bug in `OnChainNumberPad`, line 84
Probably caused by the "," character in the formatted dollar value

### PR DESCRIPTION
**Pull request by pwltr**
closes https://github.com/synonymdev/bitkit/issues/263

### Changes
- fix logic of Onchain, Receive & Lightning NumberPads
- fix(settings): CoinSelection screen background color
- fix(settings): page title capitalization
- fix(ui): icon color

### Notes
Some workarounds to fix issues with the NumberPads that deal with amounts. Code is not pretty but most of the issues should be fixed while avoiding a complete rewrite.

### Preview

https://user-images.githubusercontent.com/8538369/187992320-9ae1e273-3472-4d1f-84de-1bdd7d7b5487.mp4

### CODE REVIEW

**Comment by limpbrains** [comment]
Let's show this to Aldert

**Review by MiguelMedeiros — APPROVED** [review]

**Comment by pwltr** [comment]
Adding a "thousand" button for `NumberPad` when unit is set to sats.

**Review by limpbrains — APPROVED** [review]

**Comment by limpbrains** [comment]
Maybe in next PR ?

> Adding a "thousand" button for `NumberPad` when unit is set to sats.

Maybe in next PR ?

**Comment by pwltr** [comment]
Sure 👍

**Pull request merged**
