### PR TITLE
Share LDK logs

### PR DESCRIPTION
**Pull request by Jasonvdb**
Zips up newest 10 logs files and uses react-native-share to share it

### CODE REVIEW

**Comment by coreyphillips** [comment]
I'm able to successfully export 10 logs from a live Android device on mainnet, however, they appear to be empty.

Screen Shot 2022-12-15 at 8 35 31 AM

**Comment by coreyphillips** [comment]
Upgrading `react-native-ldk` to 0.0.77 seems to prevent Bitkit from generating invoices and appears to have trouble updating claimable/pending balances when testing on an Android device (Pixel 6 Pro) using mainnet.

**Comment by Jasonvdb** [comment]
Empty log files in zip should be patched

**Comment by coreyphillips** [comment]
It works! LGTM

**Review by coreyphillips — APPROVED** [review]

**Pull request merged**
