### PR TITLE
feat: update widgets

### LINKED ISSUE #633: [Feature]: Allow multiple widgets of the same type
### Describe the problem

As a user I want to be to add multiple widgets of the same type. E.g. multiple Bitcoin Price widgets to allow me to have different BTC/fiat pairs on my home screen.

### Describe the solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pwltr**
### Description

Updates widgets UI to design prototype v39 and moves them to web-relay.

### Linked Issues/Tasks

Replaces https://github.com/synonymdev/bitkit/pull/1169
Closes https://github.com/synonymdev/bitkit/issues/633
https://app.asana.com/0/0/1205132561089041/f

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [x] Detox test
- [ ] Unit test
- [ ] No test

### CODE REVIEW

**Comment by pwltr** [comment]
Looks like feeds are not reachable from CI for some reason.

**Comment by limpbrains** [comment]
Looking at the video from test run, I can see It can fetch feed description and later fails with "undefined is not a function" error

So, feeds are pretty much reachable

**Comment by pwltr** [comment]
Interesting, didn't know about the video for e2e tests!

Locally, tests keep hanging because of network requests to feeds:

```
09:19:05.693 detox[80834] i The app is busy with the following tasks:
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• Run loop "Main Run Loop" is awake.
• The event "Network Request" is taking place with object: "URL: “https://dht-relay.synonym.to/staging/web-relay/subscribe/azswe48ifp8gmk3p44e7futnxp6dxjm6izbgdyy96nqk8876xtty/Bitcoin%20Price/feed/BTCUSD-last”".
09:19:15.695 detox[80834] i The app is busy with the following tasks:
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• Run loop "Main Run Loop" is awake.
• The event "Network Request" is taking place with object: "URL: “https://dht-relay.synonym.to/staging/web-relay/subscribe/azswe48ifp8gmk3p44e7futnxp6dxjm6izbgdyy96nqk8876xtty/Bitcoin%20Price/feed/BTCUSD-last”".
```

I think event streams are not supported in detox, although I can't find anything on that when looking for similar issues.

EDIT: I forgot to set `.env` correctly, subscriptions are actually disabled for e2e tests, so this should not be the issue

**Comment by pwltr** [comment]
Tests are passing now except for LNURL e2e tests, but that's probably not because of anything in this PR. Should be ready for review @limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by limpbrains** [comment]
I have same error on my machine:
```
error: Error: Unable to resolve module web-streams-polyfill/ponyfill/es6 from /Users/limp/s/bitkit/node_modules/react-native-polyfill-globals/src/readable-stream.js: web-streams-polyfill/ponyfill/es6 could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  2 |
  3 | export const polyfill = () => {
> 4 |     const { ReadableStream } = require('web-streams-polyfill/ponyfill/es6');
    |                                         ^
  5 |
  6 |     polyfillGlobal('ReadableStream', () => ReadableStream);
  7 | };
    at ModuleResolver.resolveDependency (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 4)
    at async Graph._processModule (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/limp/s/bitkit/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
    at async Promise.all (index 0)
   ```

**Comment by pwltr** [comment]
Should be fixed now, just a small merge mistake.

**Pull request merged**
