### PR TITLE
fix: splash screen

### LINKED ISSUE #248: Onboarding: left space on the splash screen
**Describe the bug**
On the splash screen there is a space on the left.

**To Reproduce**
1. Turn on the app
2. Check the splash screen on the left.

**Expected behavior**
The splash screen should not have that left space and be fullscreen.

**Screenshots**

https://user-images.githubusercontent.com/5798170/184364942-b13ea4df-4699-4a08-a0a3-cd805821cc14.mp4

**Smartphone (please complete the following information):**
 - OS: Android Emulator - Pixel 2

### PR DESCRIPTION
**Pull request by limpbrains**
- for android we have logo without gradient for now
- for ios fixing filename of the logo to show on start

### CODE REVIEW

**Comment by MiguelMedeiros** [comment]
I've tested here. 
It is centered with fullscreen. But for some reason I get this screen for 1 second before showing the correct design.

## Preview
image

https://user-images.githubusercontent.com/5798170/186185128-03bcecc6-bb1b-4989-85a5-2d2659bb44e0.mp4

**Comment by limpbrains** [comment]
@MiguelMedeiros do you have same frame on main branch? Maybe icon, but without white border?

**Comment by MiguelMedeiros** [comment]
> @MiguelMedeiros do you have same frame on main branch?

Yep, same on the master branch.

> Maybe icon, but without white border?

Yes, it should fix the problem.

**Comment by MiguelMedeiros** [comment]
@limpbrains or you could fix this icon in another PR. :+1:

**Review by MiguelMedeiros — APPROVED** [review]

**Pull request merged**
