### PR TITLE
new Empty wallet component

### PR DESCRIPTION
**Pull request by limpbrains**
image

### CODE REVIEW

**Comment by MiguelMedeiros** [comment]
Hey @limpbrains ! 
I'm testing your PR on my Android Emulator, and here is how the layout it's appearing to me:

- The space between the `total balance` and the `new empty wallet component` is too big (you set to 35%).
- The `new empty wallet component` component is too big to fit on the screen and I able to scroll down, feels weird that scroll.

https://user-images.githubusercontent.com/5798170/178501466-6cb65afe-9f1a-49bb-a66f-ac060536e685.mp4

**Comment by limpbrains** [comment]
Fixed. Thanks, Miguel!

image

**Review by coreyphillips — APPROVED** [review]

**Comment by MiguelMedeiros** [comment]
I'm still able to scroll the screen. Would it be possible to limit the size to 100% of the view height, to avoid scrolling?

https://user-images.githubusercontent.com/5798170/178822455-ca0cb5de-0182-4d28-bacf-7d273c37f245.mp4

**Review by Jasonvdb — APPROVED** [review]

**Comment by limpbrains** [comment]
> I'm still able to scroll the screen. Would it be possible to limit the size to 100% of the view height, to avoid scrolling?
> empty-wallet-review-2.mp4

fixed

**Review by MiguelMedeiros — APPROVED** [review]

**Pull request merged**
