### PR TITLE
fix: address generation on address type switch

### PR DESCRIPTION
**Pull request by limpbrains**
- fixing a typo `getReceiveAddress` func. It still can fail if addresses is empty. Should we run updateAddressIndexes there?
- run `updateAddressIndexes` on addressType change
- change default addressType

### CODE REVIEW

**Comment by pwltr** [comment]
I still don't get an address. Cleaned emulator, went directly to Receive flow without changing any settings.

**Comment by limpbrains** [comment]
Yeah, there is another bug in `updateAddressIndexes` :(

**Comment by limpbrains** [comment]
fixed issue in `updateAddressIndexes` it didn't wait for all the promises to be resolved first.
this caused `refreshWallet` to exit without addresses in redux store.

I think bug is not completely resolved. There is a chance that you will tap on receive button too fast while there will be no generated addresses available. We should render UI only if we already have them. But this should be a separate PR.

@pwltr please, test again. I don't have this issue on android anymore

**Comment by pwltr** [comment]
Issue still there for me on iOS and Android.

**Review by coreyphillips — APPROVED** [review]

**Pull request merged**
