### PR TITLE
fix(ui): android splash screen

### LINKED ISSUE #1782: [Bug]: Android splash screen header/footer
### Describe the bug

The top and bottom colors for the splash screen (and the home screen after) are inconsistent. It should be all orange and then all black.

### Reproduce

1. Launch app
2. The top of the screen is black (should be orange)
3. Sometimes after the splash screen the bottom stays orange

### Screenshots / Recording

I don't have screenshots right now.

### Operating system

Android (on device)

### Bitkit version

master

### Log output

_No response_

### LINKED ISSUE #1788: [Bug]: Orange flash when enabling keyboard for recovery input on Android
### Describe the bug

The orange theme shows up when revealing the keyboard at the seed-phase input screen on Android (not iOS afaict). This feels unintentional and looks garish against the dark theme. It doesn't behave this way when opening the keyboard at other screens such as manual address input.

### Reproduce

1. On an Andriod device
2. Start clean Bitkit
3. Restore wallet
4. Display device's software keyboard
5. Observe temporary bright orange background in the area where the keyboard is expanding

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/ff0a924e-67e7-49ae-88f3-120a1b308489

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

### Log output

_No response_

### PR DESCRIPTION
**Pull request by pwltr**
### Description

Fixes splash screen and app colors on Android.

### Linked Issues/Tasks

Closes #1782 #1788 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

Before:

https://github.com/synonymdev/bitkit/assets/8538369/3f4519d2-7f22-461d-a542-21e8463fe44c

After:

https://github.com/synonymdev/bitkit/assets/8538369/5b348e22-2dca-41b0-8fef-13f84e2d7a22

### CODE REVIEW

**Review by ovitrif — APPROVED** [review]
Nice fix of everything related to splash screen and its theme colors ❤️

**Comment by catch-21** [comment]
Tested on v118.
Mostly ok but for me the bottom of the screen is only black if my system is in dark mode. When in light mode it is not black, see screenshots:

-----

Light mode:



-----

Dark mode:



-----

@pwltr  Are we happy with that or always want it black?

**Comment by pwltr** [comment]
@catch-21 What's your device & Android version? Briefly tested this on my Pixel with Android 14 and the navigation bar is black for both themes.

**Comment by catch-21** [comment]
I also observe Pixel 8 (A14), Pixel 7 (A13) and Pixel 6 (A12) always show dark native buttons.

Devices affected by light/dark mode regardless of native buttons used (gesture or 3 button):
- My Xiaomi Poco F3, Xiaomi HyperOS 1.1.0.TKHEUXM, Android 13 TKQ1.221114.001
- Xiaomi 12 Pro(Android 12 MIUI 13.0.9)
- Redmi Note 12 Pro (Android 12)
- Samsung S4 (Android 14)
- OnePlus 7T (Android 10)

**Comment by catch-21** [comment]
Verified on 8de4fa74f41be7613c28bbcd36be93d50948aa74 using my Poco F3

**Pull request merged**
