### PR TITLE
fix: reset activity store when switching network

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Review by pwltr — APPROVED** [review]

**Comment by coreyphillips** [comment]
Does resetting the activity store and switching back to the network with the previous activity repopulate the activities list?

**Comment by coreyphillips** [comment]
As a future todo, we may want to split up the activity store by networks to resemble the other stores so we can toggle between them as we switch.

**Comment by limpbrains** [comment]
> Does resetting the activity store and switching back to the network with the previous activity repopulate the activities list?

yes. There activity store will be repopulated on wallet refresh action

**Comment by limpbrains** [comment]
> As a future todo, we may want to split up the activity store by networks to resemble the other stores so we can toggle between them as we switch.

agree

**Pull request merged**
