### PR TITLE
 feat: use LDK backups 

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

- use LDK backup lib/server to store all wallet backups data
- update LDK and remove old methods

### Type of change

Refactoring

### Tests

No test

### QA Notes

Make sure that settings, widgets, contacts and lightning history is can be successfully backedup/restored

### CODE REVIEW

**Comment by coreyphillips** [comment]
Having some issues backing up `bitkit_settings` with the message "`lastErrorMessage: "Invalid backup server response (400)"`"


Simulator Screenshot - iPhone 14 - 2024-02-05 at 11 58 19

**Comment by limpbrains** [comment]
Yes, we need to update server so it accepts new backups

**Comment by limpbrains** [comment]
Or you can test it using docker testing image

**Comment by limpbrains** [comment]
Staging has been updated

**Review by coreyphillips — APPROVED** [review]

**Pull request merged**
