### PR TITLE
fix: expose rescan error to the user

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

Orignal error message is overwritten, we need to expose it to the user

### Linked Issues/Tasks

https://app.asana.com/0/1201997517565379/1207677258911336/f

### Type of change

Bug fix

### Tests

No test

### CODE REVIEW

**Comment by pwltr** [comment]
Please double check with the [toasts spreadsheet](https://docs.google.com/spreadsheets/d/1oWFQe9Ras8_1UO7cuaQFgQkpJYRr6BtlrsCVWUb5M6k/edit?pli=1#gid=0). I think we have it generic like this so users don't get confused by technical language.

**Comment by Jasonvdb** [comment]
> Please double check with the [toasts spreadsheet](https://docs.google.com/spreadsheets/d/1oWFQe9Ras8_1UO7cuaQFgQkpJYRr6BtlrsCVWUb5M6k/edit?pli=1#gid=0). I think we have it generic like this so users don't get confused by technical language.

It's just for a custom build to help debug something, should be on a separate branch

**Comment by JeanlChristophe** [comment]
What should we do here?

**Comment by limpbrains** [comment]
Original issue is closed

**Pull request closed without merging**
