### PR TITLE
UI: use native Alerts

### PR DESCRIPTION
**Pull request by pwltr**
_tbd_

### CODE REVIEW

**Comment by pwltr** [comment]
@limpbrains Could you please check if the option for Alert `userInterfaceStyle: 'dark'` works on your iOS? [It should work](https://snack.expo.dev/n7uXEtGO5) but for some reason it is not rendering in dark mode for me on the simulator. Maybe it is a simulator issue?

Would like to replace our custom `<Dialog />` with the native alerts to avoid the bugs and sometimes freezes we're seeing.

**Comment by limpbrains** [comment]
> @limpbrains Could you please check if the option for Alert `userInterfaceStyle: 'dark'` works on your iOS? [It should work](https://snack.expo.dev/n7uXEtGO5) but for some reason it is not rendering in dark mode for me on the simulator. Maybe it is a simulator issue?
> 
> Would like to replace our custom `<Dialog />` with the native alerts to avoid the bugs and sometimes freezes we're seeing.

Doesn't work for me either :(

Can we just use 
```
{show && <View><Modal /><View>}
```

hack or it doesn't solve all the problems?
Animation still works in this case

**Comment by pwltr** [comment]
Ok thanks for checking. Yes your solution could work. There is also [this issue](https://github.com/synonymdev/bitkit/issues/937) and I remember trying something similar with `{show && <Modal />}` but maybe the additional `<View />` makes the difference? Let me try.

**Comment by limpbrains** [comment]
I don't think #937 is related to Alerts. 
Same thing happens to me when I do reset throught Dev menu.

**Comment by pwltr** [comment]
> I don't think #937 is related to Alerts. Same thing happens to me when I do reset throught Dev menu.

Okay I wasn't 100% sure. Then that's a separate issue and for the Dialogs we can do the above solution 👍

**Pull request closed without merging**
