### PR TITLE
New settings menu structure

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
## Description

- New `settings menu` restructure.
- Styled a modal for `reset suggestions`
- Fixed the GlowBackground componente when bottomRight position was set.
- Fixed transparent background styles of `SettingsView` List component.
- Fixed minor typescripts warnings.

## Preview

https://user-images.githubusercontent.com/5798170/175454220-a814d436-8e84-4c2e-9ff0-428f9ab2dbd5.mp4

### CODE REVIEW

**Review by Jasonvdb — CHANGES_REQUESTED** [review]
@MiguelMedeiros getting a weird background view on iOS

https://user-images.githubusercontent.com/5300488/175896605-11355101-7fa4-4995-8254-754bcc28f280.mp4

**Comment by MiguelMedeiros** [comment]
Hey @Jasonvdb thanks for the feedback!

The transition effect of the menus is strange, apparently the IOS hides one screen over the other. I had to remove the "black" background from the menu, otherwise the glowing effect would look ugly. I think that's why this transition bug happened.

I'll try to solve this, but I'm having problems testing with IOS.

Question: Do I have any way to emulate an IOS on my PC (not a MAC)?

**Comment by MiguelMedeiros** [comment]
Hey @Jasonvdb ! 

I could not find a way to test in IOS yet. :(
But I've set the background of the container view to black.
Can you check it out on IOS for me? Thanks!

**Comment by Nuhvi** [comment]
On my M1 @MiguelMedeiros 

https://user-images.githubusercontent.com/40009100/176610860-7d524e5f-3911-4eb2-bf90-03963908e627.mov

**Comment by MiguelMedeiros** [comment]
@Nazeh so it's working now! :) 
@Jasonvdb can you review it for me?

**Review by Jasonvdb — APPROVED** [review]

**Pull request merged**
