### PR TITLE
feat(send): auto parse clipboard payment data on App open

### PR DESCRIPTION
**Pull request by pwltr**
### Changes
- split up `App.tsx` into `AppOnboarded.tsx` that has a wallet and the `SlashtagsContext`
- add Settings option to `enableAutoReadClipboard` on App start (and when it comes back to the foreground)
- `readClipboardInvoice` to parse clipboard payment data and navigate to Send flow

### Notes
Only on-chain for now. Couldn't test on iOS because clipboard + simulator is weird on M1. 

### Preview

https://user-images.githubusercontent.com/8538369/196679368-4b7838c0-1ccc-4877-8724-42d8c2641bf7.mov

### CODE REVIEW

**Review by limpbrains — COMMENTED** [review]
Can't we use same code for
main qrcode scanner, clipboard parsing, deeplinks ?

**Comment by pwltr** [comment]
Having trouble reusing the scanner code tbh, I think we need to refactor/split up some parts there so it's more reusable. Or do you mean something else?

**Comment by limpbrains** [comment]
I'm not sure about this feature, wouldn't it be too annoying?
Good thing that it is disabled by default

cc @coreyphillips

**Comment by coreyphillips** [comment]
Ideally, the if condition [here](https://github.com/synonymdev/bitkit/pull/537/files#diff-b68464d3cd0381c84114f108920e13595b2d7b7e177a8589b6b2af55d53f3eaeR31) should be handled by `processInputData`, but as you mentioned we would first need to split out logic to create a method that returns a boolean on whether or not the clipboard data is recognizable. If it is, then we forward it to `processInputData` to handle it as needed. This implementation is fine for now, but we should mark this (splitting out a method to determine whether we can or cannot handle certain data or at least implement a way to silent notifications in `processInputData`) as a future TODO item.

**Review by coreyphillips — APPROVED** [review]

**Pull request merged**
