### PR TITLE
refactor: switch from @synonymdev/react-native-keychain to react-native-keychain-manager

### PR DESCRIPTION
**Pull request by coreyphillips**
### Description
- Replaces `@synonymdev/react-native-keychain` dependency with `react-native-keychain-manager`.

### Type of change
- [x] Refactoring (improving code without creating new functionality)

### Tests
- [x] No test

### QA Notes

We'll want to ensure that both iOS & Android apps using the previous implementation migrate over smoothly to the new implementation.

### CODE REVIEW

**Review by limpbrains — CHANGES_REQUESTED** [review]
jest mock file is missing, I think we can reuse 
__mocks__/@synonymdev/react-native-keychain/index.ts

**Comment by coreyphillips** [comment]
Might want to put a pin in this for now. Looking at recent PR's for [v9.0.0](https://github.com/oblador/react-native-keychain/releases/tag/v9.0.0) that include the UI freeze we're experiencing [here](https://github.com/oblador/react-native-keychain/pull/658).

**Comment by DorianMazur** [comment]
Hi, I'm the author of react-native-keychain-manager and a maintainer of react-native-keychain. I'll be adding support for AndroidDataStore in react-native-keychain soon. :) 

I created react-native-keychain-manager because I lost contact with @oblador and couldn’t merge pull requests, but that issue has been resolved.

**Comment by coreyphillips** [comment]
> Hi, I'm the author of react-native-keychain-manager and a maintainer of react-native-keychain. I'll be adding support for AndroidDataStore in react-native-keychain soon. :)
> 
> I created react-native-keychain-manager because I lost contact with @oblador and couldn’t merge pull requests, but that issue has been resolved.

Hey @DorianMazur, thanks for the heads up! We'll keep an eye out and resume testing once AndroidDataStore support is merged.

**Comment by DorianMazur** [comment]
@coreyphillips [9.2.0](https://github.com/oblador/react-native-keychain/releases/tag/v9.2.0) is ready! Also consider using AES_GCM or AES_GCM_NO_AUTH, because AES_CBC is now deprecated.

**Comment by pwltr** [comment]
PR to switch back to upstream `react-native-keychain` v9.2.2 and AES_GCM_NO_AUTH [here](https://github.com/synonymdev/bitkit/pull/2360)

**Pull request closed without merging**
