### PR TITLE
feat: send to slashtag url

### PR DESCRIPTION
**Pull request by limpbrains**
Because the way we handle slashtag url now depends on the context (if you scan it from main screen, contact will be open, if you scan it from send form, we will try to get slash pay and send to it) processInputData now accepts new parameter - `source`. It also now accepts slashtagssdk, so we can resolve slashpay of remote profiles.

All other places where slashtags is used are now also use `processInputData`, this allows unified workflow

https://user-images.githubusercontent.com/155891/192774316-ee19954e-71d4-4976-8e0b-cf38514b340a.mp4

### CODE REVIEW

**Comment by Nuhvi** [comment]
Interesting, probably a better solution than what I was considering (creating a navigator for Slashtags that sends you where to the apropriate screen) but this applies to slashpay too.

Will try to fork this to add Feeds and Auth as well.

**Comment by limpbrains** [comment]
As I understand, Auth and Feeds with have different prefix, ike `slashauth:...` , right? These urls should be handled in `processInputData` and user should be redirected to new Screens that can handle them

**Review by pwltr — APPROVED** [review]

**Comment by Nuhvi** [comment]
@limpbrains Paying to a contact with no valid address adds the contact in the `to` input field, but no send button obviously, but I wonder if this is the intended UX? how to tell the user that there is no way to pay that person?

**Comment by limpbrains** [comment]
> @limpbrains Paying to a contact with no valid address adds the contact in the `to` input field, but no send button obviously, but I wonder if this is the intended UX? how to tell the user that there is no way to pay that person?

fixed that, now it will show an error

**Pull request merged**
