### PR TITLE
feat: Implement Auth For Testing

### PR DESCRIPTION
**Pull request by coreyphillips**
### Description
- Adds `react-native-pubky` as a dependency.
- Implements auth from` react-native-pubky`.
- Adds enough of the UI to test scanning a pubky auth url and confirm the authorization.

### QA Notes
- Scan the following qrcode and press authorize:

Screenshot 2024-09-18 at 8 27 15 AM

- URL: `pubkyauth:///?caps=/pub/pubky.app/:rw,/pub/foo.bar/file:r&secret=U55XnoH6vsMCpx1pxHtt8fReVg4Brvu9C0gUBuw-Jkw&relay=http://167.86.102.121:4173/`

    - If the url no longer works please feel free to ask me for another or you can generate one in rust using:
      - `match client.auth_request("http://167.86.102.121:5173/", &capabilities)`

### Type of change
- [x] New feature (non-breaking change which adds functionality)

### Tests
- [x] No test

https://github.com/user-attachments/assets/3e7acd15-5d9c-48d3-8a94-4bab953b1d86

### CODE REVIEW

**Comment by coreyphillips** [comment]
Not sure what to do about the tests until we make the pubky repos public.

**Comment by limpbrains** [comment]
Consider adding a NPM API key to GitHub Secrets for accessing the package. Additionally, ensure that outsiders cannot trigger tests through PR.

**Comment by pwltr** [comment]
Maybe try pulling from Github for now? `"@synonymdev/react-native-pubky": "pubky/react-native-pubky"`

But I think the repo is missing some files in the `.yarn` folder as well. Check the `.gitignore` for what should be committed.

**Comment by coreyphillips** [comment]
No luck there. I'm happy to just keep this branch up-to-date and merge it in once we go public.

**Comment by limpbrains** [comment]
We are using yarn, does npmrc work for it ?

**Review by limpbrains — APPROVED** [review]

**Pull request merged**
