### PR TITLE
fix(wallet): Upgrade beignet

### PR DESCRIPTION
**Pull request by coreyphillips**
### Description
- Upgrades beignet to `0.0.19`.
- Dev Mode Only: Allows devs to set p2tr/taproot addresses as the wallets default.
- Adds p2tr/taproot support to AddressViewer without need for dev mode.
- `p2tr` was added to the wallet structure as migration 34.
- Adds `addressTypesToMonitor` to reduce bandwidth for unused address types.
- Removed unused `create-hmac` dependency.
- Beignet upgrade also contains bug fix for `p2sh` input calculations.

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Tests
- [x] No test

### QA Notes

- With this change, only the selected address type (bech32 default) will be monitored for new wallets similar to before the Beignet migration. As address types are selected from the the Address Preference view, address types will get push to an array for continued monitoring during subsequent sessions. Restored wallets will add all address types for monitoring during the wallet creation/restore flow.
- Taproot address support is currently soft-blocked behind dev mode for testing and available to view in the AddressViewer without needing to switch to dev mode.

### CODE REVIEW

**Comment by pwltr** [comment]
After a first successful tx to a taproot address (regtest) I can't seem to send another one:

https://github.com/synonymdev/bitkit/assets/8538369/1776c316-d114-4817-a644-742155d33f39

**Comment by coreyphillips** [comment]
Issue created [here](https://github.com/synonymdev/bitkit/issues/1528). This PR is mostly to get Bitkit up-to-date with Beignet for some bug fixes. Taproot was just a requirement that needed to be handled with the upgrade. We'll need another round of testing for taproot addresses prior to removing the soft-block in a future release. We could hard block it if you feel it necessary, but thought it might be good for us devs to slowly start testing so left it in for dev mode instead.

**Comment by coreyphillips** [comment]
> After a first successful tx to a taproot address (regtest) I can't seem to send another one:

Should be resolved as of [this](https://github.com/synonymdev/bitkit/pull/1527/commits/b643710d428d111ba394e8acaa3f33bbc0403cf7) commit.

**Comment by pwltr** [comment]
Not sure this was caused by this PR so won't block but onchain feels pretty broken to me:

- I couldn't switch (to my local) electrum server
- Made a bunch of transactions from another simulator
- receive notifications popped up randomly, sometimes on sender side after send
- balance suddenly 0, restarted app, after that I had a wrong balance and duplicated receives, other tx 'removed from mempool'

https://github.com/synonymdev/bitkit/assets/8538369/5ac12153-df6b-46e3-b32f-0784b80b264f

EDIT: ok all of this seems to come from the electrum connection being quite bugged

**Comment by coreyphillips** [comment]
> Not sure this was caused by this PR so won't block but onchain feels pretty broken to me:
> 
> * I couldn't switch (to my local) electrum server
> * Made a bunch of transactions from another simulator
> * receive notifications popped up randomly, sometimes on sender side after send
> * balance suddenly 0, restarted app, after that I had a wrong balance and duplicated receives, other tx 'removed from mempool'
> 
> EDIT: ok all of this seems to come from the electrum connection being quite bugged

Have an Electrum fix coming in a separate PR.

**Review by pwltr — APPROVED** [review]

**Pull request merged**
